# Application
application:
    authentication:
        enabled: true
    authorization:
        enabled: true

# JWT
jwt:
    exp-in-millis: 7200000
    iss: ${APP_JWT_ISSUER}
    secret: ${APP_JWT_BASE_SECRET}
    sign-alg: HS256

# Server
server:
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain,multipart/form-data,application/octet-stream
    http:
        port: 8080
    http2:
        enabled: true
    port: 8443
    servlet:
        context-path: /messenger/api/v1
    ssl:
        enabled: true
        # In production move this data to secret vault
        key-alias: messenger-service
        key-store: classpath:keystore/messenger-service.p12
        key-store-password: ${APP_SERVER_SSL_KEY_STORE_PASSWORD}
        key-store-type: PKCS12

# Spring
spring:
    data:
        redis:
            host: localhost
            port: 6379
            server:
                start-by-app: false
            timeout: 1000
    servlet:
        multipart:
            max-request-size: 50MB
            max-file-size: 30MB
    cache:
        type: redis
    redis:
        host: localhost
        port: 6379
        server:
            start-by-app: false
        timeout: 5000
    datasource:
        driver-class-name: org.postgresql.Driver
        initialize: true
        password: ${APP_DB_PASSWORD}
        url: jdbc:postgresql://${APP_DB_HOST}:${APP_DB_PORT}/${APP_DB_NAME}
        username: ${APP_DB_USERNAME}
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
    sql:
        init:
            mode: always
            schema-locations: classpath*:database/schema.sql
    # Flyway migration tool properties
    flyway:
        enabled: false
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://${APP_DB_HOST}:${APP_DB_PORT}/${APP_DB_NAME}
        username: ${APP_DB_USERNAME}
        password: ${APP_DB_PASSWORD}
        schemas: migrations
        locations: classpath:/db/migration/postgresql

# S3
s3:
    # Storage
    storage:
        endpoint: s3.filebase.com
        bucket: ${APP_S3_STORAGE_BUCKET_NAME}
        signingRegion: us-east-1
        access-key: aaa
        secret-key: aaa

# Certificate
trust:
    # In production move this data to secret vault
    store: classpath:keystore/messenger-service.p12
    store.password: ${APP_TRUST_STORE_PASSWORD}

# Yandex Cloud
yandex:
    cloud:
        object-storage:
            account:
                access:
                    key:
                        id: ${APP_YANDEX_CLOUD_STORAGE_ACCOUNT_ACCESS_KEY}
                secret:
                    key: ${APP_YANDEX_CLOUD_STORAGE_ACCOUNT_SECRET}
            endpoint: https://storage.yandexcloud.net
            bucket: ${APP_S3_STORAGE_BUCKET_NAME}
    disk:
        service:
            access-token: ${APP_YANDEX_DISK_SERVICE_ACCESS_TOKEN}
            refresh-token: aaa
